# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

APPLY_FIXES: all
FLAVOR_SUGGESTIONS: false
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true

ENABLE:
  - ACTION
  - BASH
  - EDITORCONFIG
  - JSON
  - MARKDOWN
  - SPELL
  - YAML

DISABLE_LINTERS:
  - JSON_V8R
  - MARKDOWN_MARKDOWNLINT
  - SPELL_CSPELL
  - YAML_V8R

PRE_COMMANDS:
  - command: apk add --no-cache yq
    cwd: root
  - command: yq -i ".cache_domains |= sort_by(.name)" cache_domains.json
    cwd: workspace
  - command: |
      for f in *.txt; do
        sort -uo ${f} ${f}
      done
    cwd: workspace

POST_COMMANDS:
  - command: find . -user root -group root -exec chown ${USER}:${GROUP} {} \;
    cwd: workspace
